development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rms
  username: postgres
  password: foobar
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: postgres
  password: foobar
